# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('colour', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('created', models.DateField()),
            ],
        ),
    ]
